<?php

namespace App\Console\Commands;

use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Support\Str;

#[Signature('module:make-mcp-tool {name : Nombre de la Tool MCP} {module : Nombre del módulo}')]
#[Description('Crea una nueva Tool MCP dentro de un módulo')]
class ModuleMakeMcpToolCommand extends Command
{
    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $name = $this->argument('name');
        $module = $this->argument('module');

        $modulePath = base_path("Modules/{$module}");

        if (! is_dir($modulePath)) {
            $this->error("✗ El módulo '{$module}' no existe en: {$modulePath}");

            return self::FAILURE;
        }

        $suffix = 'Tool';
        $className = Str::endsWith($name, $suffix) ? $name : $name.$suffix;

        $relativePath = "Mcp/Tools/{$className}.php";
        $fullPath = "{$modulePath}/app/{$relativePath}";
        $directory = dirname($fullPath);

        if (! is_dir($directory)) {
            mkdir($directory, 0755, true);
        }

        if (file_exists($fullPath)) {
            $this->error("✗ La tool ya existe: Modules/{$module}/app/{$relativePath}");

            return self::FAILURE;
        }

        $namespace = "Modules\\{$module}\\Mcp\\Tools";

        $stub = $this->buildStub($namespace, $className);

        file_put_contents($fullPath, $stub);

        $this->info("MCP Tool [Modules/{$module}/app/{$relativePath}] created successfully.");

        return self::SUCCESS;
    }

    private function buildStub(string $namespace, string $className): string
    {
        return <<<PHP
        <?php

        namespace {$namespace};

        use Illuminate\Contracts\JsonSchema\JsonSchema;
        use Laravel\Mcp\Request;
        use Laravel\Mcp\Response;
        use Laravel\Mcp\Server\Attributes\Description;
        use Laravel\Mcp\Server\Tool;

        #[Description('A description of what this tool does.')]
        class {$className} extends Tool
        {
            /**
             * Handle the tool request.
             */
            public function handle(Request \$request): Response
            {
                //

                return Response::text('The content generated by the tool.');
            }

            /**
             * Get the tool's input schema.
             *
             * @return array<string, JsonSchema>
             */
            public function schema(JsonSchema \$schema): array
            {
                return [
                    //
                ];
            }
        }
        PHP;
    }
}
