<?php

namespace App\Console\Commands;

use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Support\Str;

#[Signature('module:make-mcp-prompt {name : Nombre del Prompt MCP} {module : Nombre del módulo}')]
#[Description('Crea un nuevo Prompt MCP dentro de un módulo')]
class ModuleMakeMcpPromptCommand extends Command
{
    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $name = $this->argument('name');
        $module = $this->argument('module');

        $modulePath = base_path("Modules/{$module}");

        if (! is_dir($modulePath)) {
            $this->error("✗ El módulo '{$module}' no existe en: {$modulePath}");

            return self::FAILURE;
        }

        $suffix = 'Prompt';
        $className = Str::endsWith($name, $suffix) ? $name : $name.$suffix;

        $relativePath = "Mcp/Prompts/{$className}.php";
        $fullPath = "{$modulePath}/app/{$relativePath}";
        $directory = dirname($fullPath);

        if (! is_dir($directory)) {
            mkdir($directory, 0755, true);
        }

        if (file_exists($fullPath)) {
            $this->error("✗ El prompt ya existe: Modules/{$module}/app/{$relativePath}");

            return self::FAILURE;
        }

        $namespace = "Modules\\{$module}\\Mcp\\Prompts";

        $stub = $this->buildStub($namespace, $className);

        file_put_contents($fullPath, $stub);

        $this->info("MCP Prompt [Modules/{$module}/app/{$relativePath}] created successfully.");

        return self::SUCCESS;
    }

    private function buildStub(string $namespace, string $className): string
    {
        return <<<PHP
        <?php

        namespace {$namespace};

        use Laravel\Mcp\Request;
        use Laravel\Mcp\Response;
        use Laravel\Mcp\Server\Attributes\Description;
        use Laravel\Mcp\Server\Prompt;
        use Laravel\Mcp\Server\Prompts\Argument;

        #[Description('A description of what this prompt does.')]
        class {$className} extends Prompt
        {
            /**
             * Handle the prompt request.
             */
            public function handle(Request \$request): Response
            {
                //

                return Response::text('The content generated by the prompt.');
            }

            /**
             * Get the prompt's arguments.
             *
             * @return array<int, Argument>
             */
            public function arguments(): array
            {
                return [
                    //
                ];
            }
        }
        PHP;
    }
}
